"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load secret environment variables from local .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'fallback-unsafe-key-for-dev')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = []


# --- APPLICATION CONFIGURATION ---

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Required by allauth
    
    # Third-party packages
    'corsheaders',      
    'rest_framework',   
    'rest_framework.authtoken', # Required for token-based auth
    'dj_rest_auth',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',   # Google Auth Provider
    'allauth.socialaccount.providers.facebook', # Facebook Auth Provider
    
    # Local apps
    'analyzer',
]

SITE_ID = 1

# --- MODERN ALLAUTH CONFIGURATION SCHEMATICS ---
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_UNIQUE_EMAIL = True
# Removed ACCOUNT_SIGNUP_FIELDS to eliminate configuration warnings/halts


# --- MIDDLEWARE INTERCEPTORS ---

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Must stay on top to allow React requests
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',  
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # --- ALLAUTH AUTHENTICATION MIDDLEWARE LAYER ---
    'allauth.account.middleware.AccountMiddleware',
    'core.middleware.DashboardAccessMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI Application entry point mapping
WSGI_APPLICATION = 'core.wsgi.application'


# --- DATABASE STRUCTURING ---

DB_USER = os.getenv('DB_USER', '')
DB_PASSWORD = os.getenv('DB_PASSWORD', '')
DB_HOST = os.getenv('DB_HOST', '')
DB_PORT = os.getenv('DB_PORT', '')
DB_NAME = os.getenv('DB_NAME', '')

MONGO_URI = os.getenv('MONGO_URI', '')
MONGO_DB_NAME = os.getenv('MONGO_DB_NAME', '')

DATABASES = {
    # SQL Primary Relational Database (PostgreSQL if environment keys exist, SQLite fallback)
    'default': {
        'ENGINE': 'django.db.backends.postgresql' if DB_USER and DB_NAME else 'django.db.backends.sqlite3',
        'NAME': DB_NAME if DB_USER and DB_NAME else BASE_DIR / 'db.sqlite3',
        'USER': DB_USER,
        'PASSWORD': DB_PASSWORD,
        'HOST': DB_HOST,
        'PORT': DB_PORT,
    },
    # MongoDB Secondary Document Pool (using djongo, SQLite fallback)
    'malware_sandbox_pool': {
        'ENGINE': 'djongo' if MONGO_URI else 'django.db.backends.sqlite3',
        'CLIENT': {
            'host': MONGO_URI,
        } if MONGO_URI else {},
        'NAME': MONGO_DB_NAME if MONGO_URI and MONGO_DB_NAME else BASE_DIR / 'db_sandbox.sqlite3',
    }
}

# Automated router script to keep local database tables cleanly separated
DATABASE_ROUTERS = ['core.db_routers.MalwareIntelRouter']

# --- EMAIL TRANSMISSION ENGINE CONFIGURATION ---
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
if EMAIL_HOST_USER:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
    EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
    DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'BlueIntel Security <noreply@blueintel.com>')
else:
    # Local developer debug output - prints email body & code straight to console window
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'BlueIntel Security <noreply@blueintel.com>'

# --- AES CONFIGURATION ENCRYPTION WRAPPER KEYS ---
ENCRYPTION_KEY = os.getenv('ENCRYPTION_KEY', '')


# --- PASSWORD VALIDATION METRICS ---

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# --- INTERNATIONALIZATION RULES ---

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# --- STATIC FILES CONFIGURATION ---

STATIC_URL = 'static/'

# CORS Permissions Allowing Frontend Transmission Links From React
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]
CORS_ALLOW_CREDENTIALS = True


# --- AUTHENTICATION BACKENDS CONFIGURATION ---
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',             # Standard database credentials
    'allauth.account.auth_backends.AuthenticationBackend',    # Allauth engine provider
]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- STATIC SOCIAL APP DEFINITIONS ---
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': os.getenv('GOOGLE_CLIENT_ID', ''),
            'secret': os.getenv('GOOGLE_CLIENT_SECRET', ''),
            'key': ''
        },
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    },
    'facebook': {
        'APP': {
            'client_id': os.getenv('FACEBOOK_CLIENT_ID', ''),
            'secret': os.getenv('FACEBOOK_CLIENT_SECRET', ''),
            'key': ''
        },
        'SCOPE': [
            'email',
            'public_profile',
        ],
        'AUTH_PARAMS': {
            'auth_type': 'rerequest',
        }
    }
}

# --- BYPASS INTERMEDIATE OAUTH SCREENS ---
SOCIALACCOUNT_LOGIN_ON_GET = True
ACCOUNT_LOGOUT_ON_GET = True

# --- OAUTH SUCCESS REDIRECT ROUTING ---
LOGIN_REDIRECT_URL = 'http://127.0.0.1:5173/login?auth=success'
LOGOUT_REDIRECT_URL = 'http://127.0.0.1:5173/'

# Point to your isolated core/adapters.py file (prevents AppRegistryNotReady circular errors)
SOCIALACCOUNT_ADAPTER = 'core.adapters.CustomSocialAccountAdapter'

# --- REST FRAMEWORK GLOBAL CONFIGURATION MATRIX ---
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
}