# Generated by Django 6.0.6 on 2026-07-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatAnalysisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size_bytes', models.BigIntegerField()),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('md5', models.CharField(blank=True, max_length=32, null=True)),
                ('sha1', models.CharField(blank=True, max_length=40, null=True)),
                ('entropy', models.FloatField()),
                ('is_pe', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pe_metadata', models.JSONField(blank=True, default=dict)),
                ('yara_matches', models.JSONField(blank=True, default=list)),
                ('extracted_iocs', models.JSONField(blank=True, default=dict)),
                ('malware_classification', models.JSONField(blank=True, default=dict)),
                ('ai_generated_report', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
