# Generated by Django 6.0.7 on 2026-07-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_threatanalysislog_virus_total_report_useractivitylog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatIntelligenceFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_value', models.CharField(max_length=255, unique=True)),
                ('indicator_type', models.CharField(max_length=50)),
                ('threat_actor', models.CharField(default='UNKNOWN', max_length=100)),
                ('malware_family', models.CharField(default='UNKNOWN', max_length=100)),
                ('severity', models.CharField(default='HIGH', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='threatanalysislog',
            name='compiler_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='threatanalysislog',
            name='digital_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='threatanalysislog',
            name='embedded_strings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='threatanalysislog',
            name='mitre_attack',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='threatanalysislog',
            name='persistence_techniques',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='threatanalysislog',
            name='scan_duration_seconds',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='threatanalysislog',
            name='status',
            field=models.CharField(default='COMPLETED', max_length=50),
        ),
        migrations.AddField(
            model_name='threatanalysislog',
            name='status_detail',
            field=models.CharField(default='Completed successfully.', max_length=255),
        ),
        migrations.AddField(
            model_name='threatanalysislog',
            name='suspicious_apis',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
