# Generated by Django 6.0.7 on 2026-07-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_threatintelligencefeed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivitylog',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='status',
            field=models.CharField(default='SUCCESS', max_length=50),
        ),
    ]
