# Generated by Django 6.0.7 on 2026-07-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_useractivitylog_details_useractivitylog_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('question', models.TextField()),
                ('ai_response', models.TextField()),
                ('related_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('analysis_id', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('response_time_seconds', models.FloatField(default=0.0)),
                ('model_used', models.CharField(default='claude-3-5-sonnet-20241022', max_length=100)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
